# OSV Scanner Configuration
# Documentation: https://google.github.io/osv-scanner/configuration/

# Vulnerabilities to ignore
# Format: ["vulnerability-id"]
# Reason for ignoring should be documented in comments

[[IgnoredVulns]]
id = "GHSA-ffrw-9mx8-89p8"
# Reason: Low severity (CVSS 2.9) vulnerability in fast-redact
# - fast-redact is a transitive dependency of pino (logging library)
# - No fixed version available as of 2025-10-12
# - Risk: ReDoS in non-performance-critical paths
# - Mitigation: Not exploitable in our usage patterns (structured logging only)
# - Will re-evaluate when upstream releases a fix
# Issue: https://github.com/davidmarkclements/fast-redact/security/advisories
