openapi: 3.1.0
info:
  title: Example API
  version: 0.1.0
paths:
  /sum:
    post:
      operationId: sum
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a: { type: number }
                b: { type: number }
              required: [a, b]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: { type: number }
