name: Auto-Merge Version PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    name: Enable Auto-Merge for Version PRs
    runs-on: ubuntu-latest
    # Only run for non-draft PRs with the specific title
    if: |
      github.event.pull_request.title == 'chore: version packages' && 
      !github.event.pull_request.draft

    steps:
      - name: Enable Auto-Merge
        run: |
          echo "Enabling auto-merge for PR #${{ github.event.pull_request.number }}"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Add Auto-Merge Comment
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🤖 **Auto-merge enabled**

          This version PR will be automatically merged once all required status checks pass.

          If you need to make additional changes before release:
          1. Disable auto-merge with: \`gh pr merge --disable-auto PR_NUMBER\`
          2. Make your changes
          3. Re-enable auto-merge or merge manually

          _This is an automated process. See [README](../blob/main/README.md#automated-release-process) for details._"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
