name: Auto-Merge Version PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    name: Enable Auto-Merge for Version PRs
    runs-on: ubuntu-latest
    # Only run for PRs created by github-actions bot
    if: github.actor == 'github-actions[bot]' && !github.event.pull_request.draft

    steps:
      - name: Check PR Title
        id: check
        run: |
          if [[ "${{ github.event.pull_request.title }}" == "chore: version packages" ]]; then
            echo "is_version_pr=true" >> $GITHUB_OUTPUT
            echo "✅ This is a version PR - will enable auto-merge"
          else
            echo "is_version_pr=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Not a version PR - skipping auto-merge"
          fi

      - name: Enable Auto-Merge
        if: steps.check.outputs.is_version_pr == 'true'
        run: |
          echo "Enabling auto-merge for PR #${{ github.event.pull_request.number }}"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Add Auto-Merge Comment
        if: steps.check.outputs.is_version_pr == 'true'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🤖 **Auto-merge enabled**

          This version PR will be automatically merged once all required status checks pass.

          If you need to make additional changes before release:
          1. Disable auto-merge with: \`gh pr merge --disable-auto PR_NUMBER\`
          2. Make your changes
          3. Re-enable auto-merge or merge manually

          _This is an automated process. See [README](../blob/main/README.md#automated-release-process) for details._"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
