name: Auto-Merge Version PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    name: Enable Auto-Merge for Version PRs
    runs-on: ubuntu-latest
    # Only run for non-draft PRs with the specific title
    if: |
      github.event.pull_request.title == 'chore: version packages' && 
      !github.event.pull_request.draft

    steps:
      - name: Check for PAT
        run: |
          if [ -z "${{ secrets.AUTO_MERGE_PAT }}" ]; then
            echo "::error::AUTO_MERGE_PAT secret is not configured."
            echo "::error::Auto-merge requires a Personal Access Token with 'repo' scope."
            echo "::error::Please follow the setup instructions in README.md"
            echo ""
            echo "To set up AUTO_MERGE_PAT:"
            echo "1. Go to https://github.com/settings/tokens/new"
            echo "2. Create a token with 'repo' scope"
            echo "3. Add it as a secret named AUTO_MERGE_PAT in repository settings"
            exit 1
          fi
          echo "✅ AUTO_MERGE_PAT is configured"

      - name: Enable Auto-Merge
        # Note: This requires a PAT with repo scope or GitHub App token
        # The default GITHUB_TOKEN cannot enable auto-merge
        # See README for setup instructions
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Attempting to enable auto-merge for PR #${PR_NUMBER}"

          # Verify this is actually a version PR from changesets
          PR_AUTHOR=$(gh pr view "${PR_NUMBER}" --json author --jq '.author.login')
          case "$PR_AUTHOR" in
            "github-actions[bot]"|"github-actions"|"app/github-actions")
              # allowed bot authors, continue
              ;;
            *)
              echo "::warning::PR author is '$PR_AUTHOR', not github-actions bot. Skipping auto-merge for security."
              exit 0
              ;;
          esac

          gh pr merge --auto --squash "${PR_NUMBER}" || {
            echo "::error::Failed to enable auto-merge for PR #${PR_NUMBER}"
            echo "::error::This usually means the PAT doesn't have the required permissions."
            echo "::error::Ensure AUTO_MERGE_PAT has 'repo' scope."
            exit 1
          }
        env:
          # Use PAT (required for auto-merge to work)
          GH_TOKEN: ${{ secrets.AUTO_MERGE_PAT }}
          GH_REPO: ${{ github.repository }}

      - name: Add Auto-Merge Comment
        if: success()
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          gh pr comment "${PR_NUMBER}" --body "🤖 **Auto-merge enabled successfully!**

          This version PR will be automatically merged once all required status checks pass.

          To make changes before release:
          1. Disable auto-merge: \`gh pr merge --disable-auto ${PR_NUMBER}\`
          2. Make your changes
          3. Re-enable auto-merge: \`gh pr merge --auto --squash ${PR_NUMBER}\`

          _See [README](../blob/main/README.md#automated-release-process) for details._"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
