name: Auto-Merge Version PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    name: Enable Auto-Merge for Version PRs
    runs-on: ubuntu-latest
    # Only run for non-draft PRs with the specific title
    if: |
      github.event.pull_request.title == 'chore: version packages' && 
      !github.event.pull_request.draft

    steps:
      - name: Enable Auto-Merge
        # Note: This requires a PAT with repo scope or GitHub App token
        # The default GITHUB_TOKEN cannot enable auto-merge
        # See README for setup instructions
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Attempting to enable auto-merge for PR #${PR_NUMBER}"

          # Verify this is actually a version PR from changesets
          PR_AUTHOR=$(gh pr view "${PR_NUMBER}" --json author --jq '.author.login')
          if [[ "$PR_AUTHOR" != "github-actions[bot]" ]] && [[ "$PR_AUTHOR" != "github-actions" ]]; then
            echo "::warning::PR author is not github-actions bot. Skipping auto-merge for security."
            exit 0
          fi

          gh pr merge --auto --squash "${PR_NUMBER}" || {
            echo "::warning::Could not enable auto-merge. This requires a PAT with 'repo' scope."
            echo "::warning::See README.md for instructions on setting up auto-merge."
            exit 0
          }
        env:
          # Use PAT if available, fallback to GITHUB_TOKEN (which will fail but not break the workflow)
          GH_TOKEN: ${{ secrets.AUTO_MERGE_PAT || secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Add Auto-Merge Comment
        if: success()
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          gh pr comment "${PR_NUMBER}" --body "🤖 **Auto-merge status**

          This version PR will be automatically merged once all required status checks pass.

          If auto-merge was not enabled (due to missing PAT), you can:
          - Manually enable it: \`gh pr merge --auto --squash ${PR_NUMBER}\`
          - Or merge manually once checks pass: \`gh pr merge --squash ${PR_NUMBER}\`

          To make changes before release:
          1. Disable auto-merge: \`gh pr merge --disable-auto ${PR_NUMBER}\`
          2. Make your changes
          3. Re-enable auto-merge or merge manually

          _See [README](../blob/main/README.md#automated-release-process) for details._"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
