name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  attestations: write
  id-token: write
  security-events: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise + install tools from mise.toml
        uses: jdx/mise-action@v3
        with:
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm test
      - run: pnpm build
      - name: Generate SBOMs
        run: pnpm sbom
      - name: Attest build provenance (SLSA)
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'dist/**'
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise + install tools from mise.toml
        uses: jdx/mise-action@v3
        with:
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm install --frozen-lockfile
      - name: OSV Scanner (full)
        uses: google/osv-scanner-action/full-scan@v1
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
