name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  attestations: write
  id-token: write
  security-events: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # pnpm + Node (both cached)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js (cached)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm audit --audit-level critical
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm test

      - name: Generate SBOMs
        run: pnpm sbom

      - name: Build
        run: pnpm build

      - name: Attest build provenance (SLSA)
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/**'

      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v2
        with:
          subject-name: 'agentic-node-ts-starter'
          subject-digest: ${{ format('sha256:{0}', github.sha) }}
          sbom-path: 'sbom.cdx.json'

  osv-scan:
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.1'

  codeql:
    permissions:
      security-events: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
