name: Main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write
  attestations: write
  security-events: write
  actions: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      node-version: '22'
      pnpm-version: '10.0.0'
    permissions:
      contents: read
      security-events: write
      actions: read

  cd:
    name: CD
    needs: [ci]
    uses: ./.github/workflows/cd.yml
    with:
      node-version: '22'
      pnpm-version: '10.0.0'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
      attestations: write
