name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  # Quick validation - all checks run in parallel
  validate:
    uses: ./.github/workflows/reusable-validate.yml
    with:
      upload-coverage: true

  # CodeQL security scanning
  codeql:
    uses: ./.github/workflows/reusable-security.yml
    with:
      generate-sbom: false
      run-osv-scan: false
      run-codeql: true

  # OSV vulnerability scanning using official Google action
  osv-scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2

  # Changeset check - runs in parallel with other jobs
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false
          standalone: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Changeset status
        run: pnpm changeset:status

  # Final status check - ensures all jobs passed
  pr-status:
    needs: [validate, codeql, osv-scan-pr, changeset]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          if [ "${{ needs.validate.result }}" != "success" ] || \
             [ "${{ needs.codeql.result }}" != "success" ] || \
             [ "${{ needs.osv-scan-pr.result }}" != "success" ] || \
             [ "${{ needs.changeset.result }}" != "success" ]; then
            echo "❌ PR validation failed"
            exit 1
          fi
          echo "✅ All PR checks passed"
