name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      node-version: '22'
      pnpm-version: '10.0.0'
    permissions:
      contents: read
      security-events: write
      actions: read
