name: Release Assets

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  release-assets:
    name: Generate and Attach Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build

      - name: Generate SBOM
        run: pnpm sbom

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/**'

      - name: Attest SBOM
        uses: actions/attest-sbom@v2
        with:
          subject-path: 'dist/**'
          sbom-path: 'sbom.cdx.json'

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v2
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}

            See the [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.

            ### Artifacts
            - 📦 SBOM (CycloneDX format) attached below
            - ✅ Build provenance attestation available
            - ✅ SBOM attestation available
          artifacts: sbom.cdx.json
          allowUpdates: true
          makeLatest: true
